/* ============================================================
   task2.js — Scheduled Reports prototype (data + behavior).

   Beginner note: same pattern as the Task 1 prototype — one
   `state` object, one render function per region, plain JS.
   The data at the top plays the backend.

   Business note: the product idea in one line — Zanko already
   MAKES the reports; this feature is how they REACH people.
   A schedule = source report + cadence + recipients (each with
   an audience version) + delivery rules. Everything else
   (approval, history, failure handling) exists to make an
   automated send trustworthy in a regulated environment.
   ============================================================ */

// ---------- data ----------

const SCHEDULES = [
  {
    id: 1, name: "Weekly Complaint Review → Sponsor Bank",
    source: "Weekly Complaint Review", cadence: "Weekly · Mon 7:00 AM",
    nextRun: "Mon Jul 6, 7:00 AM", owner: "dana.reyes@lender-demo.com",
    review: true, status: "approval",
    recipients: [
      { email: "reports@sponsorbank-demo.com", ext: true,  ver: "Full" },
      { email: "compliance-team@lender-demo.com", ext: false, ver: "Full" },
      { email: "vp-risk@lender-demo.com", ext: false, ver: "Executive" },
    ],
    history: [
      { at: "Mon Jun 29, 7:04 AM", what: "Full ×2 · Executive ×1", st: "Delivered", by: "approved by dana.reyes" },
      { at: "Mon Jun 22, 7:02 AM", what: "Full ×2 · Executive ×1", st: "Delivered", by: "approved by dana.reyes" },
    ],
  },
  {
    id: 2, name: "Monthly Executive Summary",
    source: "Weekly Complaint Review", cadence: "Monthly · last day, 5:00 PM",
    nextRun: "Fri Jul 31, 5:00 PM", owner: "leo.park@fintech-demo.com",
    review: false, status: "sent",
    recipients: [{ email: "priya.n@fintech-demo.com", ext: false, ver: "Executive" }],
    history: [{ at: "Tue Jun 30, 5:00 PM", what: "Executive ×1", st: "Delivered", by: "auto-sent" }],
  },
  {
    id: 3, name: "Ops Team Weekly Detail",
    source: "CMS Insights Dashboard", cadence: "Weekly · Fri 4:00 PM",
    nextRun: "Fri Jul 3, 4:00 PM", owner: "leo.park@fintech-demo.com",
    review: false, status: "failed",
    failNote: "Last run Fri Jun 26: 1 of 2 delivered — j.moss@fintech-demo.com bounced. Owner notified.",
    recipients: [
      { email: "ops-leads@fintech-demo.com", ext: false, ver: "Full" },
      { email: "j.moss@fintech-demo.com", ext: false, ver: "Full" },
    ],
    history: [{ at: "Fri Jun 26, 4:01 PM", what: "Full ×2", st: "1 of 2 delivered — 1 bounce", by: "auto-sent" }],
  },
];

// The report content used by the email previews — same numbers as the
// brief's illustrative "Weekly Complaint Review" so it reads familiar.
const REPORT = {
  title: "Weekly Complaint Review",
  sub: "Acme Bank · Week of Jun 22 – Jun 28, 2026 · Generated by Ask Zanko",
  verdict: "Overall: improving — resolution is faster and escalations are flat, but two themes are rising.",
  summary:
    "Complaint volume rose 12% week-over-week, driven mainly by billing disputes tied to a payment-processor outage on Tuesday. Escalations were flat, and average resolution time improved by half a day. Two themes are worth watching: unauthorized charges and autopay failures, both up sharply from last week.",
  kpis: [
    { v: "1,284", l: "Total complaints",  d: "▲ 12% WoW",  bad: true },
    { v: "7.4%",  l: "Escalation rate",   d: "▼ 0.3 pts",  bad: false },
    { v: "1.9 d", l: "Avg. resolution",   d: "▼ 0.5 d",    bad: false },
    { v: "31",    l: "High-risk cases",   d: "▲ 6 WoW",    bad: true },
  ],
  themes: [
    ["Unauthorized charges", "214", "▲ 38%", "High"],
    ["Autopay failures", "186", "▲ 29%", "Medium"],
    ["Billing disputes", "173", "▲ 11%", "Medium"],
    ["Account access", "98", "▼ 4%", "Low"],
    ["Fees & charges", "71", "▼ 9%", "Low"],
  ],
};

// ---------- state ----------

let state = {
  view: "list",        // list | create | approve
  schedules: JSON.parse(JSON.stringify(SCHEDULES)),
  openHistory: null,   // schedule id with history expanded
  pvMode: "full",      // preview: full | exec | phone
  reviewToggle: true,  // create form: review-before-send
  showExecPv: false,   // approve view: exec version folded by default
};

// ---------- views ----------

function setView(v) { state.view = v; render(); }

function toggleHistory(id) {
  state.openHistory = state.openHistory === id ? null : id;
  render();
}

// Approving is the whole point of Dana's Monday: review the rendered
// email, one click, done — instead of an hour of rebuilding it by hand.
function approveSend(id) {
  const s = state.schedules.find((x) => x.id === id);
  s.status = "sent";
  s.history.unshift({ at: "now", what: "Full ×2 · Executive ×1", st: "Delivered", by: "approved by dana.reyes" });
  state.view = "list";
  render();
}

// Failures retry in one click; the history keeps the record either way.
function retry(id) {
  const s = state.schedules.find((x) => x.id === id);
  s.status = "sent";
  s.failNote = null;
  s.history.unshift({ at: "now", what: "Full ×1 (retry)", st: "Delivered", by: "retried by leo.park" });
  render();
}

function togglePause(id) {
  const s = state.schedules.find((x) => x.id === id);
  s.status = s.status === "paused" ? "sent" : "paused";
  // resuming restores the schedule's own next run (from the source data)
  s.nextRun = s.status === "paused" ? "— paused" : SCHEDULES.find((x) => x.id === id).nextRun;
  render();
}

// ---------- render: schedules list ----------

const $ = (sel) => document.querySelector(sel);

const STATUS = {
  sent:     { cls: "sent",     label: "✓ Sent" },
  approval: { cls: "approval", label: "● Awaiting approval" },
  failed:   { cls: "failed",   label: "⚠ Delivery failed" },
  paused:   { cls: "paused",   label: "⏸ Paused" },
};

function rowAction(s) {
  if (s.status === "approval") return `<button class="btn-primary" onclick="setView('approve')">Review &amp; approve</button>`;
  if (s.status === "failed")   return `<button class="btn-primary" onclick="retry(${s.id})">Retry send</button>`;
  if (s.status === "paused")   return `<button class="btn-quiet" onclick="togglePause(${s.id})">Resume</button>`;
  return `<button class="btn-quiet" onclick="togglePause(${s.id})">Pause</button>`;
}

function renderList() {
  const rows = state.schedules.map((s) => `
    <div class="sched-row ${s.status === "failed" ? "failed" : ""}">
      <div class="st"><span class="status-chip ${STATUS[s.status].cls}">${STATUS[s.status].label}</span></div>
      <div class="nm">
        <strong>${s.name}</strong>
        <small>${s.source} · ${s.recipients.length} recipient${s.recipients.length > 1 ? "s" : ""}
          ${s.recipients.some((r) => r.ext) ? '· <span class="ext-badge">EXTERNAL</span>' : ""}
          ${s.review ? "· review before send" : ""}</small>
      </div>
      <div class="meta"><b>${s.cadence}</b>Next: ${s.nextRun}</div>
      <div>${rowAction(s)} <button class="btn-quiet" onclick="toggleHistory(${s.id})">History</button></div>
      ${s.failNote ? `<div class="fail-note">${s.failNote}</div>` : ""}
      ${state.openHistory === s.id ? `
        <div class="history">
          ${s.history.map((h) => `<div class="h-row"><b>${h.at}</b><span>${h.what}</span><span>${h.st}</span><span>${h.by}</span></div>`).join("")}
          <div class="h-row"><span>Every send is recorded — version, recipients, delivery status — and survives pausing or deletion.</span></div>
        </div>` : ""}
    </div>`).join("");

  $("#view").innerHTML = `
    <div class="toolbar" style="position:relative">
      <input placeholder="Search schedules">
      <div class="spacer"></div>
      <button class="btn-primary" onclick="setView('create')">+ New schedule</button>
    </div>
    ${rows}
    <p style="color:var(--muted); font-size:12.5px; margin-top:14px">Schedules run until paused.
    Pausing keeps the send history — it's an audit record, not just a log.</p>`;
}

// ---------- render: create flow ----------

function setPv(m) { state.pvMode = m; render(); }

function renderCreate() {
  $("#view").innerHTML = `
    <div style="margin-bottom:14px">
      <a href="#" onclick="setView('list');return false" style="color:var(--muted);font-size:13px;text-decoration:none">← Schedules</a>
      <h2 style="display:inline;margin-left:10px;font-size:16px">New schedule</h2>
    </div>
    <div class="create-grid">
      <div class="create-form">

        <section class="panel fstep">
          <h2>Source report <span class="sub">anything the Reports tab can generate, Schedules can deliver</span></h2>
          <div class="opt-row">
            <button class="opt on">Weekly Complaint Review</button>
            <button class="opt">CMS Insights Dashboard</button>
            <button class="opt">Choose another…</button>
          </div>
        </section>

        <section class="panel fstep">
          <h2>Cadence</h2>
          <div class="opt-row">
            <button class="opt on">Weekly · Monday 7:00 AM</button>
            <button class="opt">Monthly · last day</button>
            <button class="opt">Custom…</button>
          </div>
        </section>

        <section class="panel fstep">
          <h2>Recipients &amp; versions <span class="sub">one report, a version per audience</span></h2>
          <div class="recip"><span class="em">reports@sponsorbank-demo.com <span class="ext-badge">EXTERNAL</span></span>
            <span class="ver"><button class="on">Full report</button><button>Executive</button></span></div>
          <div class="recip"><span class="em">compliance-team@lender-demo.com</span>
            <span class="ver"><button class="on">Full report</button><button>Executive</button></span></div>
          <div class="recip"><span class="em">vp-risk@lender-demo.com</span>
            <span class="ver"><button>Full report</button><button class="on">Executive</button></span></div>
          <div class="recip"><input placeholder="Add recipient…" style="border:1px solid var(--line);border-radius:8px;padding:6px 10px;font:inherit;font-size:13px"></div>
        </section>

        <section class="panel fstep">
          <h2>Delivery</h2>
          <div class="field"><label>Email subject</label>Weekly Complaint Review — Acme Bank · {{week}}</div>
          <div class="toggle-row" style="margin-top:10px">
            <input type="checkbox" checked onclick="state.reviewToggle=this.checked">
            <div><strong>Review before send</strong>
              <small>On because one recipient is outside the company.</small></div>
          </div>
        </section>

        <button class="btn-primary" onclick="setView('list')">Activate schedule</button>
        <button class="btn-quiet" onclick="setView('list')">Cancel</button>
      </div>

      <div class="create-preview panel" style="position:sticky">
        <h2>Live preview <span class="sub">what each audience receives</span></h2>
        <div class="pv-tabs">
          <button class="${state.pvMode === "full" ? "on" : ""}" onclick="setPv('full')">Full report</button>
          <button class="${state.pvMode === "exec" ? "on" : ""}" onclick="setPv('exec')">Executive</button>
          <button class="${state.pvMode === "phone" ? "on" : ""}" onclick="setPv('phone')">📱 Phone</button>
        </div>
        ${renderEmail(state.pvMode)}
      </div>
    </div>`;
}

// ---------- render: email previews ----------

function kpiTiles() {
  return `<div class="kpis">${REPORT.kpis.map((k) =>
    `<div class="kpi"><b>${k.v}</b><small>${k.l}</small><span class="${k.bad ? "up" : "down"}">${k.d}</span></div>`).join("")}</div>`;
}

// The Full version mirrors the report users already generate today.
function emailFull() {
  return `<div class="email-frame">
    <div class="eh">From: Zanko Reports &lt;reports@zanko-demo.com&gt; · To: reports@sponsorbank-demo.com</div>
    <h3>${REPORT.title}</h3><div class="sub">${REPORT.sub}</div>
    <p>${REPORT.summary}</p>
    ${kpiTiles()}
    <table class="themes">
      <tr><th>Theme</th><th>Cases</th><th>WoW</th><th>Risk</th></tr>
      ${REPORT.themes.map((t) => `<tr><td>${t[0]}</td><td>${t[1]}</td><td>${t[2]}</td><td>${t[3]}</td></tr>`).join("")}
    </table>
    <div class="foot">Sent by Zanko on behalf of Acme Bank compliance ·
      <a href="#" onclick="return false">Open full data (secure link · expires in 7 days)</a><br>
      External delivery: summary in body, complaint-level data behind the expiring link.</div>
  </div>`;
}

// The Executive version answers Priya's literal question — "are we
// getting better or worse" — in its first line, then four numbers,
// then what needs attention. Readable in under a minute, no login.
function emailExec() {
  return `<div class="email-frame">
    <div class="eh">From: Zanko Reports · To: vp-risk@lender-demo.com</div>
    <h3>Executive Summary — Weekly Complaint Review</h3><div class="sub">${REPORT.sub}</div>
    <div class="verdict">${REPORT.verdict}</div>
    ${kpiTiles()}
    <div class="attn"><b>Needs attention</b>
      Unauthorized charges ▲ 38% and autopay failures ▲ 29% — both flagged high-risk and trending up
      for a second week.</div>
    <div class="foot">~1 min read · <a href="#" onclick="return false">Full report in Zanko →</a></div>
  </div>`;
}

function renderEmail(mode) {
  if (mode === "full") return emailFull();
  if (mode === "exec") return emailExec();
  return `<div class="phone-frame">${emailExec()}</div>`;
}

// ---------- render: approval view (Dana's Monday) ----------

function renderApprove() {
  $("#view").innerHTML = `
    <div style="margin-bottom:14px">
      <a href="#" onclick="setView('list');return false" style="color:var(--muted);font-size:13px;text-decoration:none">← Schedules</a>
      <h2 style="display:inline;margin-left:10px;font-size:16px">Weekly Complaint Review → Sponsor Bank</h2>
    </div>
    <div class="approve-bar" style="position:relative">
      <span>●</span>
      <div class="grow"><strong>Ready for your review</strong> — generated Mon Jul 6, 7:00 AM.
        Approving sends Full to 2 recipients (1 external) and Executive to 1.</div>
      <button class="btn-primary" onclick="approveSend(1)">Approve &amp; send</button>
      <button class="btn-quiet" onclick="setView('create')">Edit schedule</button>
    </div>
    <div style="max-width:760px">${emailFull()}
      <button class="show-more-tl" onclick="state.showExecPv=!state.showExecPv;render()">
        ${state.showExecPv ? "Hide" : "Also sending: the short executive version to 1 person — preview"} ${state.showExecPv ? "▴" : "▾"}</button>
      ${state.showExecPv ? emailExec() : ""}
    </div>`;
}

// ---------- shell ----------

function render() {
  if (state.view === "create") renderCreate();
  else if (state.view === "approve") renderApprove();
  else renderList();
  renderDemoBar();
}

// ---------- demo chrome ----------

const DEMO = [
  { key: "list",     label: "Schedules list", go: () => { resetData(); state.view = "list"; } },
  { key: "create",   label: "Create flow",    go: () => { state.view = "create"; state.pvMode = "full"; } },
  { key: "approve",  label: "Approval gate",  go: () => { resetData(); state.view = "approve"; } },
  { key: "phone",    label: "Exec email (phone)", go: () => { state.view = "create"; state.pvMode = "phone"; } },
  { key: "failed",   label: "Delivery failed", go: () => { resetData(); state.view = "list"; state.openHistory = 3; } },
];
let demoKey = "list";

function resetData() { state.schedules = JSON.parse(JSON.stringify(SCHEDULES)); state.openHistory = null; }

function setDemo(key) {
  demoKey = key;
  DEMO.find((d) => d.key === key).go();
  render();
}

function renderDemoBar() {
  $("#demo-scenarios").innerHTML = DEMO.map((d) =>
    `<button class="${demoKey === d.key ? "on" : ""}" onclick="setDemo('${d.key}')">${d.label}</button>`).join("");
}

function toggleNotes(btn) {
  document.body.classList.toggle("show-notes");
  btn.classList.toggle("on");
}

render();
